from pathlib import Path
import re
root=Path.cwd()
base=root/'._tmp/680_blender_vfx_test/capture'
base.mkdir(parents=True,exist_ok=True)
src=Path('C:/workspace/joseon-assets/reports/672_element_flight_v1/capture_tools/capture_flight.gd').read_text(encoding='utf-8')
src=src.replace('#672','#680').replace('672','680').replace('video680','video680')
src=src.replace('for label in ["fire", "cold", "lightning", "sal"]:', 'for label in ["fire_weak", "fire_strong", "sal_weak", "sal_strong"]:\n\t\tvar element := "sal" if label.begins_with("sal") else "fire"\n\t\tvar strong: bool = label.ends_with("strong")')
src=src.replace('label == "sal"','element == "sal"').replace('label != "sal"','element != "sal"').replace('label == "fire"','element == "fire"').replace('label == "cold"','element == "cold"').replace('label == "lightning"','element == "lightning"')
src=src.replace('GameState.character.spi = 150.0','GameState.character.spi = 150.0 if strong else 20.0')
src=src.replace('var area_level := 16 if element == "sal" else 1','var area_level := 16 if element == "sal" and strong else 1')
src=src.replace('report.shots[0].mult == 2.5','report.shots[0].mult == (2.5 if strong else 1.2)')
src=src.replace('normal SPI150 strength','actual SPI20/150 strength')
src=src.replace('var effects: Node = get_tree().root.get_node("Vfx")','var effects: Node = get_tree().root.get_node("Vfx")\n\tif phase != "before":\n\t\teffects.set("blender_test_enabled", true)')
src=src.replace('intended AFTER speed and travel timing differences','visual-only Blender+Godot test; identical natural mechanics and timing; SPI20/150 player, enemyLv1/16; BEFORE default false, AFTER temporary in-memory flag true')
src=src.replace('SPI150/areaLv16 high; ', 'SPI20/150 and enemyLv1/16; ')
src=src.replace('"segment": label,','"segment": label, "element": element, "strong": strong,')
src=src.replace('tracked[id] = rec','rec["visual"] = {}\n\t\t\tfor child in n.get_children():\n\t\t\t\tif child.has_meta("element_spec"):\n\t\t\t\t\trec["visual"] = {"name": str(child.name), "element_spec": child.get_meta("element_spec"), "hybrid_spec": child.get_meta("hybrid_spec", {})}\n\t\t\ttracked[id] = rec')
(base/'capture_blender.gd').write_text(src,encoding='utf-8',newline='\n')
(base/'capture_scene.tscn').write_text('[gd_scene load_steps=2 format=3]\n\n[ext_resource type="Script" path="res://._tmp/680_blender_vfx_test/capture/capture_blender.gd" id="1"]\n\n[node name="BlenderCapture680" type="Node"]\nprocess_mode = 3\nscript = ExtResource("1")\n',encoding='utf-8',newline='\n')
print('capture prepared')
