from pathlib import Path
import json
p=Path('C:/workspace/joseon/tmp/cast608')
catalog=json.loads((p/'catalog.json').read_text(encoding='utf-8'))['voices'];account=json.loads((p/'account.json').read_text(encoding='utf-8'))['voices']
by={v['voice_id']:v for v in json.loads((p/'korean.json').read_text(encoding='utf-8'))['voices']};by.update({v['voice_id']:v for v in catalog});by.update({v['voice_id']:v for v in account})
def candidate(id,why,risk):
 v=by[id];return {'voice_id':id,'name':v['name'],'why':why,'risk':risk,'description':v.get('description',''),'preview_url':v.get('preview_url'),'labels':v.get('labels',{'gender':v.get('gender'),'age':v.get('age'),'language':v.get('language')}),'in_account':id in {v['voice_id'] for v in account}}
roles=[
 {'id':'doho','name':'도호','target':'30대 안팎의 중저음. 여유·능청은 있지만 가벼운 유튜버처럼 들리지 않는 떠돌이 검객.','lines':['산책 좀 했지.','도깨비도 이사를 다니는 줄은 몰랐구먼.'],'scenes':['촌장이 소탕을 끝낸 도호에게 고맙다고 말한다. 도호는 대수롭지 않게 받아넘긴다.','도깨비가 못골에 이사를 왔다며 말을 건다. 도호는 놀라기보다 슬쩍 농을 던진다.'],'previous':['베었구려! 못골이 오랜만에 숨을 쉬겠소.','오, 개 잡은 도사 양반이로군. 덕분에 눌러앉게 됐지.'],'next':['약소하지만… 받으시오.','장터 뒤 대장간 터가 마음에 들어서 말이야.'],'old':'Ir7oQcBXWiq4oFGROCfj','candidates':[candidate('YcKXQhCnoNmbyAdL8Shk','차분하고 쿨한 결이 도호의 힘 뺀 능청에 가까운 후보.','너무 매끈하거나 현대적인 억양인지 확인.'),candidate('rCm09Tf1yMYbOyCRLDyB','중저음·자연스러운 속도·재치 있는 전달이라는 설명이 능청 대사에 맞음.','설명체·콘텐츠 진행자 느낌이 남는지 확인.'),candidate('v1is6KLMuZWgumQgKSOi','배우 기반의 정돈된 발음과 감정 깊이. 진지한 장면까지 맡길 대안.','도호보다 연령감이 높거나 광고체로 들리는지 확인.')]},
 {'id':'merchant','name':'김 영감','target':'사람 좋은 늙은 잡화상. 살짝 웃음 섞인 너스레·구수함. 촌장보다 밝고 말맛이 있어야 함.','lines':['도사 양반, 갓끈이 풀렸수. 한 번 봐드릴까?','갓이야 덤으로 줘도 검 값은 못 깎아 주우. 목숨값이니.'],'scenes':['처음 온 도호를 보고 잡화상이 장난스럽게 말을 붙인다.','손님이 검 값을 깎자고 한다. 웃음은 있지만 장사 원칙은 단호하다.'],'previous':['물건 좀 봅시다.','검 값이 좀 세구려.'],'next':['물건 좀 봅시다.','알았수. 구경이나 해 보시오.'],'old':'AgA5UKT9OrVg7jxVBZd4','candidates':[candidate('PLfpgtLkFW07fDYbUiRJ','밝고 익살스러운 노인 목소리로 김 영감의 너스레에 우선 적합.','과한 만화 연기나 지나친 고음인지 확인.'),candidate('5ON5Fnz24cnOozEQfGAm','친절한 한국인 할아버지 결로 사람 좋은 잡화상에 맞음.','너무 순하고 느려서 능청이 약해지는지 확인.'),candidate('ZZ4xhVcc83kZBfNIlIIz','유쾌한 캐릭터 목소리로 장사꾼의 말맛을 살리는 대안.','노인보다 중년처럼 들릴 수 있음.')]},
 {'id':'elder','name':'촌장','target':'지치고 걱정 많은 촌로. 담백하고 사무적이며, 감사할 때도 과장하지 않는다.','lines':['떠돌이 도사가 웬일이오.','요괴병에 장정 셋을 잃었소.'],'scenes':['낯선 도호가 마을에 들어왔다. 촌장이 경계 섞인 담백한 질문을 건넨다.','촌장이 석 달간 마을을 덮친 역병의 피해를 설명한다. 슬픔을 꾹 누른다.'],'previous':['못골 촌장이시오?','못골 장터가 닫힌 지 석 달이오.'],'next':['못골 장터가 닫힌 지 석 달이오.','내가 가 보리다.'],'old':'AgA5UKT9OrVg7jxVBZd4','candidates':[candidate('nw7o9nqXCkQKoAs59z99','나이 든 중저음과 차분한 무게로 지친 어른의 담백함을 시험.','오디오북처럼 지나치게 풍성한 낭독이 되는지 확인.'),candidate('owbiGBW4rEJjmY5Xvwwx','성숙하고 깊은 저음·절제된 호흡으로 촌장의 책임감에 맞음.','연령감이 충분한지, 너무 든든해서 피로감이 사라지는지 확인.'),candidate('NpneagLVR101ytYGxUPX','차분하고 온화한 결. 과장하지 않는 마을 실무 책임자 대안.','김 영감과 대비될 만큼 진지하고 담백한지 확인.')]},
 {'id':'shaman','name':'무당 할매','target':'나이 든 여성의 낮고 마른 결. 진중하고 근심 많은 해설자. 젊은 상담사·뉴스 낭독 느낌은 피한다.','lines':['도사 양반, 늦었소. 못골이 석 달째 이 꼴이오.','봉인이 흔들리오. 요사한 기운이 못골로 새고 있소.'],'scenes':['못골을 살필 도호가 뒤늦게 도착했다. 할매는 안도보다 걱정이 앞선다.','봉인의 이상을 감지한 할매가 도호에게 조용하고 단호하게 경고한다.'],'previous':['소문을 듣고 왔소.','무슨 일이 벌어진 게요?'],'next':['봉인이 흔들리오.','도사 양반밖에 없소.'],'old':'UvkXHIJzOBYWOI51BDKp','candidates':[candidate('SrkN8J8D7m8bAtmS0uiq','노년 여성으로 분류된 목소리. 할매의 연령감부터 맞추는 우선 후보.','포근한 이야기꾼 성향이 강해 경고의 무게가 약할 수 있음.'),candidate('ZjAPD4f11zlnEnZpKDgo','노년 여성·차분한 전달로 억지 할머니 연기 없이 자연스러움 비교.','설명에는 중년이라 표기와 실제 연령감이 다를 수 있음.'),candidate('ah4r1hZOydd3XWlHOm3Y','중저음과 약한 허스키 결로 마르고 진중한 할매의 대안.','중년 목소리라 노년감이 부족할 수 있음.')]},
 {'id':'jumo','name':'주모 / 구미호','target':'성숙한 중저음 여성. 평소엔 억척스럽고 정 많으며, 속내를 감출 때는 따뜻함이 살짝 걷힌다.','lines':['도사 양반, 목이나 축이고 가시구려. 술은… 없어도 국물은 있지.','내가 들녘 옛 주막집서… 오래 일했지. 그 얘긴, 말은 못 하겠소.'],'scenes':['손님 끊긴 술청에 도호가 들른다. 주모는 일손을 움직이며 구수하게 권한다.','옛 주막 이야기를 묻자 주모가 말을 삼킨다. 친절하지만 쉽게 속을 보이지 않는다.'],'previous':['목이 좀 마르구려.','그 옛 주막집은 아는 곳이오?'],'next':['국물이라도 한 그릇 주시오.','더 묻지는 않겠소.'],'old':'xi3rF0t7dg7uN2M0WUhr','candidates':[candidate('Kndx0DUJ5HQE1HQgiMY8','30대 중저음 여성. 젊고 밝은 기존 주모보다 성숙한 바탕을 시험.','억척스러운 생활감과 소문 줄의 말맛이 붙는지 확인.'),candidate('UqW1DivwFt1NwUMSGnTn','차분한 30대 여성. 평소의 정과 숨기는 속내 두 결을 비교하기 좋음.','너무 반듯한 상담·안내 말투인지 확인.'),candidate('VFNaRkx6q2IQZn2mmwwg','약한 지역 억양과 감정 표현이라는 설명이 술청 주인의 생활감에 맞음.','실제 목록 메타데이터가 빈약해 샘플 발음부터 확인.')]},
 {'id':'iksoe','name':'억쇠','target':'발보다 입이 바쁜 장돌뱅이. 친근하고 재빠른 중년 남성, 사투리는 양념 수준.','lines':['뭐가 들었는지는 나도 몰라유. 열어봐야 알지.','손해 봐도 내 탓은 마슈, 도사 양반. 운도 실력이랑께.'],'scenes':['억쇠가 보따리를 펼쳐 보이며 도호의 호기심을 자극한다.','도호가 손해 볼까 망설이자 억쇠가 능청스럽게 책임을 피한다.'],'previous':['그 보따리엔 뭐가 들었수?','손해 보면 어쩔 거요?'],'next':['일단 하나 열어 봅시다.','그 말이 더 수상하구려.'],'old':None,'candidates':[candidate('TRO4gatqxbbwLXHLDLSk','충청도 억양의 젊은 아저씨로 유·슈 말끝의 장돌뱅이 맛을 시험.','말이 너무 느리거나 지역 억양이 과하면 부적합.'),candidate('ZZ4xhVcc83kZBfNIlIIz','유쾌한 중년 캐릭터 결이 발 빠른 말장사 역할에 맞음.','김 영감 후보와 겹치므로 동시에 채택하지 않는 방향.'),candidate('TKUGUd5JWceSqSPVPjha','40~50대 지역 억양으로 친근한 장사꾼의 생활감 대안.','경상도 결이라 유·슈 말끝과 충돌하는지 확인.')]},
 {'id':'dokkaebi','name':'도깨비','target':'털북숭이 거한의 거친 중저음. 반말·능청은 있지만 우스꽝스러운 괴물은 아니다.','lines':['오, 개 잡은 도사 양반이로군. 개 있는 동네엔 이사를 못 오는데, 덕분에 눌러앉게 됐지.','물건을 맡기면 다른 물건으로 바꿔 줘. 값은 그때그때 달라.'],'scenes':['새로 못골에 눌러앉은 거한이 도호를 보고 웃으며 말을 건다.','도깨비가 자기 거래 규칙을 자신 있게 설명한다. 장난은 있지만 신용은 지킨다.'],'previous':['이 터엔 누구요?','무슨 일을 하는 게요?'],'next':['도깨비도 이사를 다니는 줄은 몰랐구먼.','맡긴 건 제대로 돌려주는 거겠지?'],'old':None,'candidates':[candidate('wzMVIc8FAFmgMxFpN0uM','거칠고 남성적인 한국어 결로 거한의 바탕을 먼저 맞춤.','거칠기만 하고 능청·친근함이 없는지 확인.'),candidate('UmYoqGlufKxhJ6NCx5Mv','허스키하고 야성적인 결. 오래 산 도깨비의 질감을 시험.','너무 늙거나 험악해져 신용 있는 장사꾼 느낌을 잃는지 확인.'),candidate('ibCGc01503OQd2R6i1n1','깊은 허스키 바리톤으로 큰 몸의 무게를 살릴 대안.','차분한 낭독 성향이라 반말의 자연스러움 확인.')]}
]
jobs=[]
for role in roles:
 for rank,c in enumerate(role['candidates'],1):
  c['rank']=rank
  for i,t in enumerate(role['lines']):jobs.append({'role':role['id'],'rank':rank,'voice_id':c['voice_id'],'name':c['name'],'scene':role['scenes'][i],'line':i,'file':f'audio/{role["id"]}_{rank}_{i+1}.mp3','request':{'text':t,'model_id':'eleven_v4','language_code':'ko','previous_text':role['previous'][i],'next_text':role['next'][i],'voice_settings':{'stability':0.5,'similarity_boost':0.75}}})
 if role['old']:
  for i,t in enumerate(role['lines']):jobs.append({'role':role['id'],'rank':0,'voice_id':role['old'],'name':'기존 배정 (동일 문장 재생성)','line':i,'file':f'audio/{role["id"]}_0_{i+1}.mp3','request':{'text':t,'model_id':'eleven_v4','language_code':'ko','previous_text':role['previous'][i],'next_text':role['next'][i],'voice_settings':{'stability':0.5,'similarity_boost':0.75}}})
(p/'plan.json').write_text(json.dumps({'card':608,'generated_by':'codex','model':'eleven_v4','roles':roles,'jobs':jobs,'basis':'후보 순위는 등록자 설명과 인물 사양에 따른 가안. 실제 생성 대사를 듣고 PD가 최종 판단.'},ensure_ascii=False,indent=2),encoding='utf-8')
print('PLAN',len(roles),'roles',len(jobs),'clips',sum(len(j['request']['text']) for j in jobs),'chars')
