import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const [responseFile,outputFile]=process.argv.slice(2);
if(!responseFile||!outputFile)throw Error('Usage: download_rigged.mjs <saved MCP response.json> <absolute output.glb>');
const result=JSON.parse(fs.readFileSync(responseFile,'utf8').replace(/^\uFEFF/,''));
const url=new URL(result.result.structuredContent.rigged_character_glb_url);
if(url.protocol!=='https:'||url.hostname!=='assets.meshy.ai')throw Error('Expected official Meshy signed asset URL');
if(!path.isAbsolute(outputFile)||path.extname(outputFile)!=='.glb')throw Error('Absolute GLB output required');
if(fs.existsSync(outputFile))throw Error('Output already exists; no overwrite or automatic retry');
const response=await fetch(url,{signal:AbortSignal.timeout(120000)});
if(!response.ok)throw Error(`Rigged asset HTTP ${response.status}`);
const bytes=Buffer.from(await response.arrayBuffer());
if(bytes.toString('ascii',0,4)!=='glTF'||bytes.readUInt32LE(8)!==bytes.length)throw Error('Invalid GLB payload');
fs.mkdirSync(path.dirname(outputFile),{recursive:true});
fs.writeFileSync(outputFile,bytes,{flag:'wx'});
const receipt={downloaded_at:new Date().toISOString(),source_response:path.resolve(responseFile),source_host:url.hostname,source_path:url.pathname,output:path.resolve(outputFile),byte_length:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex'),reason:'Official MCP v0.5.1 rigging download branch returns signed URLs only and ignores save_to. Downloaded only the requested GLB.'};
fs.writeFileSync(outputFile+'.download.json',JSON.stringify(receipt,null,2)+'\n');
process.stdout.write(JSON.stringify(receipt)+'\n');
